export type Language = 'zh' | 'en'

export interface Translations {
  // 通用
  common: {
    backToHome: string
    switchRole: string
    language: string
    chinese: string
    english: string
    confirm: string
    cancel: string
    save: string
    delete: string
    edit: string
    view: string
    search: string
    filter: string
    reset: string
    submit: string
    loading: string
    noData: string
    all: string
    select: string
    close: string
    back: string
  }
  
  // 角色
  roles: {
    admin: string
    bank: string
    nbfi: string
    coreEnterprise: string
    construction: string
  }
  
  // 导航
  navigation: {
    dashboard: string
    assetIssuance: string
    receivablesManagement: string
    inventoryIssuance: string
    marketTrading: string
    lending: string
    absPackaging: string
    bridge: string
    fundRecovery: string
  }
  
  // 仪表盘
  dashboard: {
    title: string
    currentRole: string
    totalAssets: string
    dailyVolume: string
    platformRevenue: string
    activeAssets: string
    userActivity: string
    avgFundingCost: string
    transactionTrend: string
    assetDistribution: string
    transactionComparison: string
    buy: string
    sell: string
    lend: string
    bridge: string
    receivable: string
    inventory: string
    // 建筑公司专用
    receivableAssets: string
    inventoryAssets: string
    pendingReceivables: string
    activeInventory: string
    marketValue: string
    // 核心企业专用
    issuedReceivables: string
    fundingCost: string
    totalLiabilities: string
    activeIssuances: string
    avgMaturity: string
    costAnalysis: string
  }
  
  // 资产发行
  assetIssuance: {
    title: string
    description: string
    receivableTab: string
    inventoryTab: string
    noPermission: string
    noPermissionDesc: string
    receivableNumber: string
    autoGenerated: string
    debtorName: string
    selectDebtor: string
    receivableAmount: string
    enterAmount: string
    dueDate: string
    selectDueDate: string
    dueDateCannotBePast: string
    contractInvoiceFile: string
    clickToUpload: string
    dragFileHere: string
    supportedFormats: string
    pdfImageFormats: string
    additionalNotes: string
    enterNotes: string
    issueQuantity: string
    autoListMarket: string
    issueToken: string
    batchIssue: string
    inventoryNumber: string
    inventoryType: string
    selectInventoryType: string
    rawMaterial: string
    workInProgress: string
    finishedProduct: string
    itemDescription: string
    enterItemDescription: string
    valuationAmount: string
    enterValuation: string
    warehouseLocation: string
    enterWarehouse: string
    photoQualityReport: string
    clickToUploadImage: string
    dragImageHere: string
    imageFormats: string
    recentIssuances: string
    noIssuanceRecords: string
    issuanceWillShowHere: string
    issued: string
    listed: string
    copyHash: string
    viewTransaction: string
    issuanceSuccess: string
    tokenIssuedSuccessfully: string
    tokenId: string
    transactionHash: string
    nextSteps: string
    tokenRecordedOnBlockchain: string
    canViewInMarketTrading: string
    hashCanQueryDetails: string
    confirm: string
    errors: {
      selectOrEnterDebtor: string
      enterReceivableAmount: string
      enterValidAmount: string
      selectDueDate: string
      uploadContractInvoice: string
      enterIssueQuantity: string
      quantityMustBeAtLeastOne: string
      onlyPdfOrImage: string
      selectInventoryType: string
      enterItemDescription: string
      enterValuationAmount: string
      enterValidValuation: string
      enterWarehouseLocation: string
      uploadPhotoOrReport: string
      onlyImageFiles: string
    }
  }
  
  // ABS打包
  absPackaging: {
    title: string
    bankOnly: string
    nbfiPurchase: string
    bankDescription: string
    nbfiDescription: string
  }
  
  // 桥接管理
  bridge: {
    title: string
    bankDescription: string
    nbfiDescription: string
    bridgeTotal: string
    bridgeFee: string
    bridgeableAssets: string
    bridgeConfig: string
    bridgeHistory: string
    selectedAssets: string
    selectedValue: string
    estimatedReceived: string
    estimatedTime: string
    targetChain: string
    recipientAddress: string
    addressValid: string
    addressInvalid: string
    previewBridge: string
    confirmBridge: string
    inProgress: string
    completed: string
    failed: string
    viewDetail: string
    bridgeId: string
    bridgeQuantity: string
    totalValue: string
    txHash: string
    viewTransaction: string
    filterByType: string
    filterByTranche: string
    allTypes: string
    receivableABS: string
    inventoryABS: string
    allTranches: string
    senior: string
    mezzanine: string
    junior: string
    holdingQuantity: string
    tokenValue: string
    bridgeQuantityLabel: string
    sourceChain: string
    bridgeSummary: string
    bridgeAssets: string
    feeDetails: string
    assetValue: string
    estimatedArrival: string
    status: string
    timestamp: string
    progress: string
    chainConfirm: string
    crossChaining: string
    targetConfirm: string
    finish: string
  }
  
  // 资金回收
  fundRecovery: {
    title: string
    description: string
    usdcBalanceOverview: string
    currentBalance: string
    todayConvertibleQuota: string
    unlimited: string
    currentExchangeRate: string
    conversionForm: string
    bankDirectConversion: string
    nbfiForexPoolConversion: string
    conversionAmount: string
    circleAccountAddress: string
    estimatedHandlingFee: string
    feeRate: string
    feeAmount: string
    forexPoolSelection: string
    currentPoolDepth: string
    exchangeRate: string
    autoMatchOptimalPool: string
    estimatedReceiveEHKD: string
    afterDeduction: string
    noHandlingFee: string
    handlingFeeNote: string
    previewConversion: string
    confirmConversion: string
    conversionSuccess: string
    eHKDReceived: string
    conversionPath: string
    amountDetails: string
    estimatedArrivalTime: string
    instantArrival: string
    forexPoolProcessing: string
    processing: string
    enterValidAmount: string
    exceedDailyLimit: string
    recoveryHistory: string
    timeline: string
    table: string
    type: string
    amount: string
    transactionHash: string
    copyHash: string
    usdcDeposit: string
    forexExchange: string
    completed: string
    inProgress: string
    failed: string
  }
  
  // 借贷管理
  lending: {
    title: string
    myCollateralizedLoans: string
    applyForNewLoan: string
    loanMarket: string
    myLoanManagement: string
    loanId: string
    collateralToken: string
    loanAmount: string
    interestRate: string
    loanTerm: string
    status: string
    operations: string
    inReview: string
    loanGranted: string
    repaying: string
    overdue: string
    earlyRepayment: string
    selectCollateralToken: string
    totalCollateralValue: string
    maxBorrowableAmount: string
    estimatedInterest: string
    submitApplication: string
    bid: string
    borrower: string
    riskScore: string
    currentLowestRate: string
    bidRate: string
    bidAmount: string
    confirmBid: string
    loanDetails: string
    basicInfo: string
    collateralInfo: string
    repaymentPlan: string
    transactionRecords: string
    nbfiDescription: string
    bankDescription: string
    lender: string
    switchRoleHint: string
    adminDescription: string
    fullAccess: string
    nbfiView: string
    bankView: string
    pendingBid: string
    bidding: string
    matched: string
    normal: string
    warning: string
    viewDetail: string
    collection: string
    totalLentAmount: string
    totalInterest: string
    badDebtRate: string
    loanStatistics: string
    loanDistribution: string
    noData: string
    noLoanRecords: string
    noPendingApplications: string
    bidableApplications: string
    collateralTokens: string
    totalCollateralValueLabel: string
    loanTermDays: string
    loanTermDaysUnit: string
    borrowerLabel: string
    riskScoreLabel: string
    currentLowestRateLabel: string
    lowRisk: string
    mediumRisk: string
    highRisk: string
    annualized: string
    issueDate: string
    dueDate: string
    bidTitle: string
    applicationInfo: string
    applicationId: string
    loanAmountLabel: string
    loanTermLabel: string
    currentLowestRateLabel2: string
    bidRateLabel: string
    required: string
    enterRate: string
    annualizedUnit: string
    rateTooHigh: string
    bidAmountLabel: string
    partialBid: string
    enterBidAmount: string
    maxBidable: string
    bidAmountExceeded: string
    estimatedInterestIncome: string
    estimatedTotalRecovery: string
    submitBid: string
    rateRangeError: string
    amountRangeError: string
    rateTooHighConfirm: string
    loanDetailTitle: string
    loanIdLabel: string
    borrowerLabel2: string
    loanAmountLabel2: string
    interestRateLabel: string
    annualizedUnit2: string
    collateralValue: string
    loanTermLabel2: string
    daysUnit: string
    issueDateLabel: string
    dueDateLabel: string
    applicationDate: string
    statusLabel: string
    tokenId: string
    type: string
    value: string
    realTimeValue: string
    principal: string
    interestEstimated: string
    total: string
    applicationSubmitted: string
    loanGranted2: string
    fundsReceived: string
    initiateLiquidation: string
    close: string
    collateralValueLabel: string
    term: string
    noLoanRecords2: string
    currentValue: string
    selectAtLeastOneToken: string
    loanAmountExceeded: string
    enterLoanAmount: string
    loanTermLabel3: string
    days7: string
    days30: string
    days90: string
    days180: string
    estimatedInterestLabel: string
    basedOnMarketRate: string
    loanStatistics2: string
    myTotalLoanAmount: string
    availableCollateral: string
    currentAverageRate: string
    repaymentCalendar: string
    noUpcomingLoans: string
    repaymentRequired: string
    receivable: string
    inventory: string
  }
  
  // 市场交易
  marketTrading: {
    title: string
    marketOverview: string
    tokenFilters: string
    watchlist: string
    recentTrades: string
    filterByType: string
    filterByStatus: string
    allTypes: string
    receivable: string
    inventory: string
    allStatus: string
    onSale: string
    soldOut: string
    searchPlaceholder: string
    purchase: string
    price: string
    quantity: string
    issuer: string
    purchaseModal: {
      title: string
      tokenInfo: string
      purchaseQuantity: string
      totalAmount: string
      confirmPurchase: string
      purchaseSuccess: string
    }
    sampleDebtors: {
      abcTech: string
      xyzEngineering: string
      defConstruction: string
    }
    sampleIssuers: {
      coreEnterpriseA: string
      coreEnterpriseB: string
      coreEnterpriseC: string
      constructionCompanyX: string
      constructionCompanyY: string
      constructionCompanyZ: string
    }
    inventoryTypes: {
      finishedProduct: string
      rawMaterial: string
      workInProgress: string
    }
    inventoryItems: {
      constructionSteel: string
      cement: string
      precastComponents: string
    }
    storageLocations: {
      shenzhenWarehouseA: string
      guangzhouWarehouseB: string
      dongguanFactoryC: string
    }
    qualityStatuses: {
      certified: string
      pendingCertification: string
    }
  }
  
  // ABS打包
  absPackaging: {
    title: string
    description: string
    bankOnly: string
    nbfiPurchase: string
    bankDescription: string
    nbfiDescription: string
    assetPool: string
    absBuilder: string
    packagedABSList: string
    selectedAssets: string
    totalValue: string
    averageRiskRating: string
    absName: string
    packagingScale: string
    riskLayering: string
    seniorTranche: string
    mezzanineTranche: string
    juniorTranche: string
    interestRate: string
    previewABS: string
    confirmPackaging: string
    packagingSuccess: string
    issuanceTime: string
    totalScale: string
    layerStatus: string
    soldOut: string
    inSale: string
    notStarted: string
    receivableTab: string
    inventoryTab: string
    searchTokenId: string
    riskLevel: string
    all: string
    lowRisk: string
    mediumRisk: string
    highRisk: string
    amountRange: string
    issuer: string
    selectedTotalValue: string
    selectedCount: string
    packagingConfig: string
    absNameLabel: string
    absNamePlaceholder: string
    assetType: string
    autoDetermined: string
    basedOnSelectedAssets: string
    expectedYield: string
    aaaRating: string
    bbbRating: string
    bbRating: string
    fixedPercentage: string
    remainingPart: string
    autoCalculated: string
    tranchePreview: string
    amount: string
    percentage: string
    issuanceSettings: string
    allowNBFIPurchase: string
    allowNBFIPurchaseDesc: string
    autoListMarket: string
    autoListMarketDesc: string
    notes: string
    notesPlaceholder: string
    reset: string
    requirements: string
    atLeastTwoAssets: string
    atLeastTwoIssuers: string
    enterAbsName: string
    myAbsProducts: string
    noAbsProducts: string
    willShowAfterPackaging: string
    type: string
    viewDetail: string
    report: string
    purchasableAbsProducts: string
    browseAbsProducts: string
    basicInfo: string
    packagingScaleLabel: string
    assetCount: string
    selectedAssetList: string
    tokenId: string
    typeLabel: string
    faceValue: string
    riskRating: string
    trancheConfig: string
    allowNBFI: string
    autoList: string
    transactionHash: string
    copyHash: string
    nextSteps: string
    absRecordedOnBlockchain: string
    canViewInList: string
    hashCanQueryDetails: string
    confirm: string
    cancel: string
    packaging: string
    processing: string
    receivableABS: string
    inventoryABS: string
    mixedABS: string
    senior: string
    mezzanine: string
    junior: string
    seniorTrancheLabel: string
    mezzanineTrancheLabel: string
    juniorTrancheLabel: string
    daysRemaining: string
    status: string
  }
  
  // 其他页面标题
  pages: {
    marketTrading: string
    lending: string
    fundRecovery: string
  }
  
  // 角色选择页面
  roleSelection: {
    title: string
    subtitle: string
    description: string
    responsibilities: string
    permissions: string
    enterButton: string
    demoMode: string
    fullDemo: string
    quickDemo: string
    freeExplore: string
    platformStats: string
    totalAssets: string
    dailyVolume: string
    activeUsers: string
    bridgeVolume: string
    resetData: string
    exportRecord: string
    switchTheme: string
    businessFlow: string
    assetIssuance: string
    marketTrading: string
    absPackaging: string
    lending: string
    bridge: string
    fundRecovery: string
      confirmReset: string
      fullDemoDesc: string
      quickDemoDesc: string
      freeExploreDesc: string
      darkTheme: string
      lightTheme: string
    }
    
    // 通用补充
    common: {
      minutes: string
      normal: string
      addressBook: string
      advancedOptions: string
      slippageProtection: string
      default: string
      gasStrategy: string
      standard: string
      fast: string
      custom: string
      items: string
      history: string
      targetChain: string
      quantity: string
      value: string
      chainConfirming: string
      blocks: string
    }
  }

const translations: Record<Language, Translations> = {
  zh: {
    common: {
      backToHome: '返回总入口',
      switchRole: '切换角色',
      language: '语言',
      chinese: '中文',
      english: 'English',
      confirm: '确认',
      cancel: '取消',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      view: '查看',
      search: '搜索',
      filter: '筛选',
      reset: '重置',
      submit: '提交',
      loading: '加载中...',
      noData: '暂无数据',
      all: '全部',
      select: '选择',
      close: '关闭',
      back: '返回',
      noPermission: '您没有权限访问此功能',
      quickActions: '一键操作',
      transactionId: '交易ID',
      operations: '操作',
      retry: '重试',
      reportIssue: '报告问题',
      description: '说明',
    },
    roles: {
      admin: '系统管理员',
      bank: '银行',
      nbfi: '非银行金融机构',
      coreEnterprise: '核心企业',
      construction: '建筑公司',
    },
    navigation: {
      dashboard: '仪表盘',
      assetIssuance: '资产发行',
      receivablesManagement: '应收账款管理',
      inventoryIssuance: '库存代币发行',
      marketTrading: '市场交易',
      lending: '借贷管理',
      absPackaging: 'ABS打包',
      bridge: '桥接管理',
      fundRecovery: '资金回收',
    },
    dashboard: {
      title: '智能仪表盘',
      currentRole: '当前角色',
      totalAssets: '总资产价值',
      dailyVolume: '今日交易量',
      platformRevenue: '平台收益',
      activeAssets: '活跃资产',
      userActivity: '用户活跃度',
      avgFundingCost: '平均融资成本',
      transactionTrend: '交易活动趋势',
      assetDistribution: '资产类型分布',
      transactionComparison: '交易类型对比',
      buy: '购买',
      sell: '出售',
      lend: '借贷',
      bridge: '桥接',
      receivable: '应收账款',
      inventory: '库存',
      // 建筑公司专用
      receivableAssets: '应收账款资产',
      inventoryAssets: '库存资产',
      pendingReceivables: '待收应收账款',
      activeInventory: '活跃库存',
      marketValue: '市场价值',
      // 核心企业专用
      issuedReceivables: '已发行应收账款',
      fundingCost: '融资成本',
      totalLiabilities: '总负债',
      activeIssuances: '活跃发行',
      avgMaturity: '平均到期日',
      costAnalysis: '成本分析',
    },
    assetIssuance: {
      title: '资产发行',
      description: '创建并发行应收账款代币或库存代币',
      receivableTab: '应收账款代币发行',
      inventoryTab: '库存代币发行',
      noPermission: '您没有资产发行权限',
      noPermissionDesc: '',
      receivableNumber: '应收账款编号',
      autoGenerated: '（系统自动生成）',
      debtorName: '债务人名称',
      selectDebtor: '请选择债务人',
      receivableAmount: '应收账款金额',
      enterAmount: '请输入金额',
      dueDate: '到期日期',
      selectDueDate: '请选择到期日期',
      dueDateCannotBePast: '到期日期不能早于今天',
      contractInvoiceFile: '合同/发票文件',
      clickToUpload: '点击上传或拖拽文件到此处',
      dragFileHere: '点击上传或拖拽文件到此处',
      supportedFormats: '支持 PDF、PNG、JPG 格式',
      pdfImageFormats: '支持 PDF、PNG、JPG 格式',
      additionalNotes: '附加说明',
      enterNotes: '请输入附加说明（可选）',
      issueQuantity: '发行数量',
      autoListMarket: '自动上架市场',
      issueToken: '发行代币',
      batchIssue: '批量发行',
      inventoryNumber: '库存编号',
      inventoryType: '库存类型',
      selectInventoryType: '请选择库存类型',
      rawMaterial: '原材料',
      workInProgress: '在制品',
      finishedProduct: '成品',
      itemDescription: '物品描述',
      enterItemDescription: '请输入物品描述',
      valuationAmount: '估值金额',
      enterValuation: '请输入估值金额',
      warehouseLocation: '所在仓库/位置',
      enterWarehouse: '请输入仓库名称或位置',
      photoQualityReport: '照片/质检报告',
      clickToUploadImage: '点击上传或拖拽图片到此处',
      dragImageHere: '点击上传或拖拽图片到此处',
      imageFormats: '支持 PNG、JPG、JPEG 格式',
      recentIssuances: '最近发行的代币',
      noIssuanceRecords: '暂无发行记录',
      issuanceWillShowHere: '发行代币后将显示在这里',
      issued: '已发行',
      listed: '已上架',
      copyHash: '复制哈希',
      viewTransaction: '查看交易',
      issuanceSuccess: '发行成功！',
      tokenIssuedSuccessfully: '代币已成功发行到区块链',
      tokenId: '代币ID',
      transactionHash: '交易哈希',
      nextSteps: '下一步操作：',
      tokenRecordedOnBlockchain: '代币已记录在区块链上',
      canViewInMarketTrading: '可以在"市场交易"中查看',
      hashCanQueryDetails: '交易哈希可用于查询交易详情',
      confirm: '确定',
      errors: {
        selectOrEnterDebtor: '请选择或输入债务人名称',
        enterReceivableAmount: '请输入应收账款金额',
        enterValidAmount: '请输入有效的金额（大于0）',
        selectDueDate: '请选择到期日期',
        uploadContractInvoice: '请上传合同或发票文件',
        enterIssueQuantity: '请输入发行数量',
        quantityMustBeAtLeastOne: '发行数量必须大于等于1',
        onlyPdfOrImage: '仅支持PDF或图像文件',
        selectInventoryType: '请选择库存类型',
        enterItemDescription: '请输入物品描述',
        enterValuationAmount: '请输入估值金额',
        enterValidValuation: '请输入有效的金额（大于0）',
        enterWarehouseLocation: '请输入所在仓库/位置',
        uploadPhotoOrReport: '请上传照片或质检报告',
        onlyImageFiles: '仅支持图像文件',
      },
    },
    absPackaging: {
      title: 'ABS打包平台',
      bankOnly: '银行专属',
      nbfiPurchase: 'NBFI购买',
      bankDescription: '将应收账款和库存代币打包成不同风险等级的ABS代币',
      nbfiDescription: '浏览和购买银行发行的ABS代币产品',
    },
    bridge: {
      title: '跨链桥接管理平台',
      bankDescription: '桥接您打包的ABS代币',
      nbfiDescription: '桥接您购买的ABS代币',
      bridgeTotal: '已桥接总额',
      bridgeFee: '桥接费用',
      bridgeableAssets: '可桥接资产',
      bridgeConfig: '桥接配置',
      bridgeHistory: '桥接历史',
      selectedAssets: '已选择资产',
      selectedValue: '选中资产总值',
      estimatedReceived: '预计到账金额',
      estimatedTime: '预计到账时间',
      targetChain: '目标区块链',
      recipientAddress: '外部钱包地址',
      addressValid: '地址格式有效',
      addressInvalid: '请输入有效的以太坊地址',
      previewBridge: '预览桥接',
      confirmBridge: '确认桥接',
      inProgress: '进行中',
      completed: '完成',
      failed: '失败',
      viewDetail: '查看详情',
      bridgeId: '桥接ID',
      bridgeQuantity: '桥接数量',
      totalValue: '总价值',
      txHash: '交易哈希',
      viewTransaction: '查看交易',
      filterByType: '按类型筛选',
      filterByTranche: '按分层筛选',
      allTypes: '全部',
      receivableABS: '应收账款ABS',
      inventoryABS: '库存ABS',
      allTranches: '全部',
      senior: 'Senior',
      mezzanine: 'Mezzanine',
      junior: 'Junior',
      holdingQuantity: '持有数量',
      tokenValue: '单代币价值',
      bridgeQuantityLabel: '桥接数量',
      sourceChain: '源链',
      bridgeSummary: '桥接摘要',
      bridgeAssets: '桥接资产',
      feeDetails: '费用明细',
      assetValue: '资产价值',
      estimatedArrival: '预计到账',
      status: '状态',
      timestamp: '时间',
      progress: '桥接进度',
      chainConfirm: '联盟链确认',
      crossChaining: '跨链中',
      targetConfirm: '目标链确认',
      finish: '完成',
      bridgePreview: '桥接预览',
      estimatedTimeValue: '约 15 分钟后',
      basicInfo: '基本信息',
      bridgeDetails: '桥接详情',
      transactionInfo: '交易信息',
      transactionHash: '交易哈希',
      copyHash: '复制哈希',
      viewOnExplorer: '在浏览器中查看',
      reBridge: '重新桥接',
      initiateBridgeRequest: '发起桥接请求',
      allianceChainConfirmation: '联盟链确认',
    },
    fundRecovery: {
      title: '资金回收与外汇兑换平台',
      description: '处理从外部公链回流USDC的兑换和资金回收流程',
      usdcBalanceOverview: 'USDC余额概览',
      currentBalance: '当前余额',
      todayConvertibleQuota: '今日可兑换额度',
      unlimited: '无限制',
      currentExchangeRate: '当前汇率',
      conversionForm: '兑换表单',
      bankDirectConversion: '银行直接兑换（Circle）',
      nbfiForexPoolConversion: 'NBFI外汇池兑换',
      conversionAmount: '兑换金额（USDC）',
      circleAccountAddress: 'Circle账户地址',
      estimatedHandlingFee: '预估手续费',
      feeRate: '手续费率：',
      feeAmount: '手续费金额：',
      forexPoolSelection: '外汇池选择',
      currentPoolDepth: '当前池深度：',
      exchangeRate: '汇率：',
      autoMatchOptimalPool: '已自动匹配最优池',
      estimatedReceiveEHKD: '预计接收eHKD',
      afterDeduction: '扣除手续费后',
      noHandlingFee: '免手续费（银行特权）',
      handlingFeeNote: '手续费1.2%，预计到账时间：2-5分钟',
      previewConversion: '预览兑换',
      confirmConversion: '确认兑换',
      conversionSuccess: '兑换成功！',
      eHKDReceived: 'eHKD已成功到账',
      conversionPath: '兑换路径',
      amountDetails: '金额明细',
      estimatedArrivalTime: '预计到账时间',
      instantArrival: '即时到账（Circle直接兑换）',
      forexPoolProcessing: '2-5分钟（外汇池处理）',
      processing: '处理中...',
      enterValidAmount: '请输入有效的兑换金额',
      exceedDailyLimit: '超过每日限额',
      recoveryHistory: '回收历史记录',
      timeline: '时间线',
      table: '表格',
      type: '类型',
      amount: '金额',
      transactionHash: '交易哈希',
      copyHash: '复制哈希',
      usdcDeposit: 'USDC入金',
      forexExchange: '外汇兑换',
      completed: '完成',
      inProgress: '处理中',
      failed: '失败',
      forexPoolStatus: '外汇池状态',
      totalLiquidity: '总流动性',
      dailyTradingVolume: '24小时交易量',
      dailyRateFluctuation: '24小时汇率波动',
      myLiquidity: '我的流动性',
      myLiquidityContribution: '我的流动性贡献',
      todayFeeRevenue: '今日手续费收益',
      annualizedYield: '年化收益率',
      addRemoveLiquidity: '添加/移除流动性',
      poolDepthChart: '池子深度图',
      realTimeConversionActivity: '实时兑换活动',
      liquidityManagement: '流动性管理',
      operationType: '操作类型',
      addLiquidity: '添加流动性',
      removeLiquidity: '移除流动性',
      liquidityAmount: '金额（eHKD）',
      enterLiquidityAmount: '请输入金额',
      addLiquidityNote: '添加流动性可获得手续费收益',
      annualizedYieldNote: '年化收益率约3.7%',
      canRemoveAnytime: '可随时移除流动性',
      removeLiquidityNote: '移除流动性将停止获得手续费收益',
      fundsReturned: '资金将立即返还到您的账户',
      minutesAgo: '分钟前',
      success: '成功',
      fullAccess: '全权限访问',
      adminDescription: '系统管理员可以使用所有兑换方式',
    },
    lending: {
      title: '借贷管理',
      myCollateralizedLoans: '我的抵押借款',
      applyForNewLoan: '申请新借款',
      loanMarket: '贷款市场',
      myLoanManagement: '我的贷款管理',
      loanId: '借款ID',
      collateralToken: '抵押代币',
      loanAmount: '借款金额',
      interestRate: '借款利率',
      loanTerm: '借款期限',
      status: '状态',
      operations: '操作',
      inReview: '审核中',
      loanGranted: '已放款',
      repaying: '还款中',
      overdue: '已逾期',
      earlyRepayment: '提前还款',
      selectCollateralToken: '选择抵押代币',
      totalCollateralValue: '总抵押价值',
      maxBorrowableAmount: '最大可借金额',
      estimatedInterest: '预估利息',
      submitApplication: '提交申请',
      bid: '投标',
      borrower: '借款方',
      riskScore: '风险评分',
      currentLowestRate: '当前最低利率',
      bidRate: '投标利率',
      bidAmount: '投标金额',
      confirmBid: '确认投标',
      loanDetails: '借款详情',
      basicInfo: '基本信息',
      collateralInfo: '抵押品信息',
      repaymentPlan: '还款计划',
      transactionRecords: '交易记录',
      nbfiDescription: '管理您的抵押借款和申请新借款',
      bankDescription: '管理您的贷款业务和投标新的借款申请',
      lender: '贷款方',
      switchRoleHint: '请在顶部导航栏切换用户角色为"NBFI"或"Bank"',
      adminDescription: '系统管理员可以查看所有借贷管理功能',
      fullAccess: '全权限访问',
      nbfiView: 'NBFI视图（借款方）',
      bankView: '银行视图（贷款方）',
      // Bank View
      pendingBid: '待投标',
      bidding: '投标中',
      matched: '已匹配',
      normal: '正常',
      warning: '预警',
      viewDetail: '查看详情',
      collection: '催收',
      totalLentAmount: '已放贷款总额',
      totalInterest: '待收利息总额',
      badDebtRate: '坏账率',
      loanStatistics: '贷款统计',
      loanDistribution: '贷款分布',
      noData: '暂无数据',
      noLoanRecords: '暂无贷款记录',
      noPendingApplications: '暂无待投标的借款申请',
      bidableApplications: '可投标的借款申请',
      collateralTokens: '抵押代币',
      totalCollateralValueLabel: '总抵押价值：',
      loanTermDays: '借款期限：',
      loanTermDaysUnit: '天',
      borrowerLabel: '借款方：',
      riskScoreLabel: '风险评分：',
      currentLowestRateLabel: '当前最低利率：',
      lowRisk: '低风险',
      mediumRisk: '中风险',
      highRisk: '高风险',
      annualized: '年化',
      issueDate: '发放日期',
      dueDate: '到期日',
      // Bid Modal
      bidTitle: '投标',
      applicationInfo: '借款申请信息',
      applicationId: '申请ID：',
      loanAmountLabel: '借款金额：',
      loanTermLabel: '借款期限：',
      currentLowestRateLabel2: '当前最低利率：',
      bidRateLabel: '投标利率',
      required: '*',
      enterRate: '请输入利率',
      annualizedUnit: '% 年化',
      rateTooHigh: '您的利率高于当前最低利率，可能无法中标',
      bidAmountLabel: '投标金额',
      partialBid: '部分投标',
      enterBidAmount: '请输入投标金额',
      maxBidable: '最大可投:',
      bidAmountExceeded: '投标金额不能超过借款金额',
      estimatedInterestIncome: '预估利息收入：',
      estimatedTotalRecovery: '预计回收总额：',
      submitBid: '提交投标',
      rateRangeError: '利率必须在0-20%之间',
      amountRangeError: '投标金额必须在0-{amount} eHKD之间',
      rateTooHighConfirm: '您提供的利率 {rate}% 高于当前最低利率 {lowestRate}%，可能无法中标。是否继续？',
      // Loan Detail Modal
      loanDetailTitle: '借款详情',
      loanIdLabel: '借款ID：',
      borrowerLabel2: '借款方：',
      loanAmountLabel2: '借款金额：',
      interestRateLabel: '利率：',
      annualizedUnit2: '年化',
      collateralValue: '抵押价值：',
      loanTermLabel2: '借款期限：',
      daysUnit: '天',
      issueDateLabel: '发放日期：',
      dueDateLabel: '到期日：',
      applicationDate: '申请日期：',
      statusLabel: '状态：',
      tokenId: '代币ID',
      type: '类型',
      value: '价值',
      realTimeValue: '实时价值',
      principal: '本金：',
      interestEstimated: '利息（预估）：',
      total: '总计：',
      applicationSubmitted: '申请提交',
      loanGranted2: '贷款发放',
      fundsReceived: '资金到账',
      initiateLiquidation: '发起清算抵押品',
      close: '关闭',
      // NBFI View
      collateralValueLabel: '抵押价值',
      term: '期限',
      noLoanRecords2: '暂无借款记录',
      currentValue: '当前价值:',
      selectAtLeastOneToken: '请至少选择一个抵押代币',
      loanAmountExceeded: '借款金额不能超过最大可借金额 {amount} eHKD',
      enterLoanAmount: '请输入借款金额',
      loanTermLabel3: '借款期限',
      days7: '7天',
      days30: '30天',
      days90: '90天',
      days180: '180天',
      estimatedInterestLabel: '预估利息：',
      basedOnMarketRate: '基于当前市场利率 {rate}% 计算',
      // NBFI Sidebar
      loanStatistics2: '借款统计',
      myTotalLoanAmount: '我的借款总额',
      availableCollateral: '可用抵押额度',
      currentAverageRate: '当前平均利率',
      repaymentCalendar: '还款日历',
      noUpcomingLoans: '暂无即将到期的借款',
      repaymentRequired: '需还款:',
      receivable: '应收账款',
      inventory: '库存',
    },
    marketTrading: {
      title: '市场交易',
      marketOverview: '市场概览',
      tokenFilters: '代币筛选',
      watchlist: '关注列表',
      recentTrades: '最近交易',
      filterByType: '按类型筛选',
      filterByStatus: '按状态筛选',
      allTypes: '全部',
      receivable: '应收账款',
      inventory: '库存',
      allStatus: '全部',
      onSale: '在售',
      soldOut: '已售罄',
      searchPlaceholder: '搜索代币...',
      purchase: '购买',
      price: '价格',
      quantity: '数量',
      issuer: '发行方',
      purchaseModal: {
        title: '购买代币',
        tokenInfo: '代币信息',
        purchaseQuantity: '购买数量',
        totalAmount: '总金额',
        confirmPurchase: '确认购买',
        purchaseSuccess: '购买成功！',
        transactionSuccess: '交易成功！',
        tokenPurchaseCompleted: '代币购买已完成',
        transactionHash: '交易哈希',
        copyHash: '复制哈希',
        confirmPurchaseTitle: '确认购买',
        unitPrice: '单价：',
        quantity: '数量：',
        subtotal: '小计：',
        platformFee: '平台费（1%）：',
        total: '总计：',
        processing: '处理中...',
        cancel: '取消',
      },
      description: '浏览和交易应收账款代币与库存代币',
      tradableTokens: '可交易代币',
      batchPurchase: '批量采购',
      debtor: '债务人',
      faceValue: '面值',
      dueDate: '到期日',
      remaining: '剩余',
      days: '天',
      annualYield: '年化收益率',
      riskRating: '风险评级',
      inventoryType: '库存类型',
      item: '物品',
      valuation: '估值',
      storageLocation: '存储位置',
      qualityStatus: '质量状态',
      addToWatchlist: '添加到观察列表',
      removeFromWatchlist: '从观察列表移除',
      marketTotalVolume: '市场总交易量',
      activeTokenCount: '活跃代币数量',
      tokens: '个代币',
      todayTransactionCount: '今日交易笔数',
      transactions: '笔交易',
      platformTotalCommission: '平台总佣金',
      today: '（今日）',
      marketChange24h: '24小时市场变化',
      comparedToYesterday: '较昨日',
      filterConditions: '筛选条件',
      reset: '重置',
      tokenType: '代币类型',
      riskLevel: '风险等级',
      all: '全部',
      lowRisk: '低风险',
      mediumRisk: '中风险',
      highRisk: '高风险',
      issuer: '发行方',
      priceRange: '价格范围',
      dueTime: '到期时间',
      withinDays: '天内',
      myWatchlist: '我的观察列表',
      noWatchedTokens: '暂无观察的代币',
      clickStarToAdd: '点击代币卡片上的星标添加',
      remove: '移除',
      recentTransactions: '最近交易',
      noTransactionRecords: '暂无交易记录',
      marketTrend: '市场趋势（7天）',
      price: '价格',
      monday: '周一',
      tuesday: '周二',
      wednesday: '周三',
      thursday: '周四',
      friday: '周五',
      saturday: '周六',
      sunday: '周日',
      buyNow: '立即购买',
      setPriceAlert: '设置价格警报',
      certified: '已认证',
      pendingCertification: '待认证',
      currentPrice: '当前价格',
      discount: '折扣',
      receivable: '应收账款',
      inventory: '库存',
      sampleDebtors: {
        abcTech: 'ABC科技有限公司',
        xyzEngineering: 'XYZ工程集团',
        defConstruction: 'DEF建设股份公司',
      },
      sampleIssuers: {
        coreEnterpriseA: '核心企业A',
        coreEnterpriseB: '核心企业B',
        coreEnterpriseC: '核心企业C',
        constructionCompanyX: '建筑公司X',
        constructionCompanyY: '建筑公司Y',
        constructionCompanyZ: '建筑公司Z',
      },
      inventoryTypes: {
        finishedProduct: '成品',
        rawMaterial: '原材料',
        workInProgress: '在制品',
      },
      inventoryItems: {
        constructionSteel: '建筑钢材',
        cement: '水泥',
        precastComponents: '预制构件',
      },
      storageLocations: {
        shenzhenWarehouseA: '深圳仓库A',
        guangzhouWarehouseB: '广州仓库B',
        dongguanFactoryC: '东莞工厂C',
      },
      qualityStatuses: {
        certified: '已认证',
        pendingCertification: '待认证',
      },
    },
    absPackaging: {
      title: 'ABS打包平台',
      description: '将应收账款和库存代币打包成不同风险等级的ABS代币',
      bankOnly: '银行专属',
      nbfiPurchase: 'NBFI购买',
      bankDescription: '将应收账款和库存代币打包成不同风险等级的ABS代币',
      nbfiDescription: '浏览和购买银行发行的ABS代币产品',
      assetPool: '可用资产池',
      absBuilder: 'ABS构建器',
      packagedABSList: '已打包ABS列表',
      selectedAssets: '已选择资产',
      totalValue: '总价值',
      averageRiskRating: '平均风险评级',
      absName: 'ABS名称',
      packagingScale: '打包规模',
      riskLayering: '风险分层配置',
      seniorTranche: '高级层',
      mezzanineTranche: '中级层',
      juniorTranche: '初级层',
      interestRate: '利率',
      previewABS: '预览ABS',
      confirmPackaging: '确认打包',
      packagingSuccess: '打包成功！',
      issuanceTime: '发行时间',
      totalScale: '总规模',
      layerStatus: '各层状态',
      soldOut: '已售罄',
      inSale: '销售中',
      notStarted: '未开始',
      receivableTab: '应收账款',
      inventoryTab: '库存',
      searchTokenId: '搜索代币ID...',
      riskLevel: '风险等级',
      all: '全部',
      lowRisk: '低风险 (A级)',
      mediumRisk: '中风险 (B级)',
      highRisk: '高风险 (C级)',
      amountRange: '金额范围',
      issuer: '发行方',
      selectedTotalValue: '选中资产总价值：',
      selectedCount: '已选择：',
      packagingConfig: '打包配置',
      absNameLabel: 'ABS名称',
      absNamePlaceholder: '例如：应收账款ABS-2025-001',
      assetType: '资产类型',
      autoDetermined: '（根据选中资产自动判断）',
      basedOnSelectedAssets: '基于选中资产总价值自动计算',
      expectedYield: '预期收益率',
      aaaRating: 'AAA级',
      bbbRating: 'BBB级',
      bbRating: 'BB级',
      fixedPercentage: '固定占比（剩余部分），自动计算',
      remainingPart: '剩余部分',
      autoCalculated: '自动计算',
      tranchePreview: '分层预览',
      amount: '金额：',
      percentage: '占比：',
      issuanceSettings: '发行设置',
      allowNBFIPurchase: '允许NBFI购买',
      allowNBFIPurchaseDesc: '允许非银行金融机构购买此ABS',
      autoListMarket: '自动上架市场',
      autoListMarketDesc: '打包完成后自动上架到交易市场',
      notes: '备注信息',
      notesPlaceholder: '输入备注信息（可选）',
      reset: '重置',
      requirements: '请完成以下要求：',
      atLeastTwoAssets: '至少选择2个资产',
      atLeastTwoIssuers: '至少选择2个不同发行方的资产以分散风险',
      enterAbsName: '输入ABS名称',
      myAbsProducts: '我的ABS产品',
      noAbsProducts: '暂无ABS产品',
      willShowAfterPackaging: '打包后将显示在这里',
      type: '类型：',
      viewDetail: '查看详情',
      report: '报告',
      purchasableAbsProducts: '可购买的ABS产品',
      browseAbsProducts: '浏览银行发行的ABS代币产品，选择适合的投资标的',
      basicInfo: '基本信息',
      packagingScaleLabel: '打包规模：',
      assetCount: '包含资产数：',
      selectedAssetList: '选中资产',
      tokenId: '代币ID',
      typeLabel: '类型',
      faceValue: '面值',
      riskRating: '风险评级',
      trancheConfig: '风险分层配置',
      allowNBFI: '允许NBFI购买：',
      autoList: '自动上架市场：',
      transactionHash: '交易哈希',
      copyHash: '复制哈希',
      nextSteps: '下一步操作：',
      absRecordedOnBlockchain: 'ABS代币已记录在区块链上',
      canViewInList: '可以在"已打包ABS列表"中查看详情',
      hashCanQueryDetails: '交易哈希可用于查询交易详情',
      confirm: '确定',
      cancel: '取消',
      packaging: '确认打包',
      processing: '正在打包...',
      receivableABS: '应收账款ABS',
      inventoryABS: '库存ABS',
      mixedABS: '混合ABS',
      senior: '高级层',
      mezzanine: '中级层',
      junior: '初级层',
      seniorTrancheLabel: '高级层 (Senior Tranche)',
      mezzanineTrancheLabel: '中级层 (Mezzanine Tranche)',
      juniorTrancheLabel: '初级层 (Junior Tranche)',
      daysRemaining: '剩余',
      status: '状态：',
    },
    pages: {
      marketTrading: '市场交易',
      lending: '借贷管理',
      fundRecovery: '资金回收',
    },
    roleSelection: {
      title: '区块链资产代币化平台',
      subtitle: 'v1.0 · 五角色协同演示系统',
      description: '点击下方角色卡片，体验不同参与方的视角',
      responsibilities: '核心职责',
      permissions: '权限特点',
      enterButton: '进入',
      demoMode: '演示模式',
      fullDemo: '完整流程演示',
      quickDemo: '快速功能演示',
      freeExplore: '自由探索模式',
      platformStats: '平台数据概览',
      totalAssets: '平台总资产',
      dailyVolume: '今日交易量',
      activeUsers: '活跃用户数',
      bridgeVolume: '跨链桥总量',
      resetData: '重置所有演示数据',
      exportRecord: '导出演示记录',
      switchTheme: '切换到',
      businessFlow: '平台核心业务流程',
      assetIssuance: '资产发行',
      marketTrading: '市场交易',
      absPackaging: 'ABS打包',
      lending: '借贷管理',
      bridge: '跨链桥接',
      fundRecovery: '资金回收',
      confirmReset: '确定要重置所有演示数据吗？',
      fullDemoDesc: '30分钟，按业务流程展示',
      quickDemoDesc: '10分钟，重点功能展示',
      freeExploreDesc: '无时间限制',
      darkTheme: '暗色主题',
      lightTheme: '亮色主题',
    },
    common: {
      minutes: '分钟',
      normal: '正常',
      addressBook: '地址簿',
      advancedOptions: '高级选项',
      slippageProtection: '滑点保护',
      default: '默认',
      gasStrategy: 'Gas费策略',
      standard: '标准',
      fast: '快速',
      custom: '自定义',
      items: '项',
      history: '历史',
      targetChain: '目标链',
      quantity: '数量',
      value: '价值',
      chainConfirming: '联盟链确认中',
      blocks: '区块',
    },
  },
  en: {
    common: {
      backToHome: 'Back to Home',
      switchRole: 'Switch Role',
      language: 'Language',
      chinese: '中文',
      english: 'English',
      confirm: 'Confirm',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      search: 'Search',
      filter: 'Filter',
      reset: 'Reset',
      submit: 'Submit',
      loading: 'Loading...',
      noData: 'No Data',
      all: 'All',
      select: 'Select',
      close: 'Close',
      back: 'Back',
      noPermission: 'You do not have permission to access this feature',
      quickActions: 'Quick Actions',
      transactionId: 'Transaction ID',
      operations: 'Operations',
      retry: 'Retry',
      reportIssue: 'Report Issue',
      description: 'Description',
    },
    roles: {
      admin: 'Administrator',
      bank: 'Bank',
      nbfi: 'NBFI',
      coreEnterprise: 'Core Enterprise',
      construction: 'Construction Company',
    },
    navigation: {
      dashboard: 'Dashboard',
      assetIssuance: 'Asset Issuance',
      receivablesManagement: 'Receivables Management',
      inventoryIssuance: 'Inventory Issuance',
      marketTrading: 'Market Trading',
      lending: 'Lending',
      absPackaging: 'ABS Packaging',
      bridge: 'Bridge',
      fundRecovery: 'Fund Recovery',
    },
    dashboard: {
      title: 'Smart Dashboard',
      currentRole: 'Current Role',
      totalAssets: 'Total Assets',
      dailyVolume: 'Daily Volume',
      platformRevenue: 'Platform Revenue',
      activeAssets: 'Active Assets',
      userActivity: 'User Activity',
      avgFundingCost: 'Avg Funding Cost',
      transactionTrend: 'Transaction Trend',
      assetDistribution: 'Asset Distribution',
      transactionComparison: 'Transaction Comparison',
      buy: 'Buy',
      sell: 'Sell',
      lend: 'Lend',
      bridge: 'Bridge',
      receivable: 'Receivable',
      inventory: 'Inventory',
      // Construction Company specific
      receivableAssets: 'Receivable Assets',
      inventoryAssets: 'Inventory Assets',
      pendingReceivables: 'Pending Receivables',
      activeInventory: 'Active Inventory',
      marketValue: 'Market Value',
      // Core Enterprise specific
      issuedReceivables: 'Issued Receivables',
      fundingCost: 'Funding Cost',
      totalLiabilities: 'Total Liabilities',
      activeIssuances: 'Active Issuances',
      avgMaturity: 'Avg Maturity',
      costAnalysis: 'Cost Analysis',
    },
    assetIssuance: {
      title: 'Asset Issue',
      description: 'Create and issue accounts receivable tokens or inventory tokens',
      receivableTab: 'Accounts Receivable Tokens',
      inventoryTab: 'Inventory Tokens',
      noPermission: 'You do not have asset issuance permission',
      noPermissionDesc: '',
      receivableNumber: 'Accounts Receivable Number',
      autoGenerated: '(Auto-generated by system)',
      debtorName: 'Debtor Name',
      selectDebtor: 'Please select debtor',
      receivableAmount: 'Accounts Receivable Amount',
      enterAmount: 'Enter amount',
      dueDate: 'Due Date',
      selectDueDate: 'Please select due date',
      dueDateCannotBePast: 'Due date cannot be earlier than today',
      contractInvoiceFile: 'Contract/Invoice File',
      clickToUpload: 'Click to upload or drag file here',
      dragFileHere: 'Click to upload or drag file here',
      supportedFormats: 'Supports PDF, PNG, JPG formats',
      pdfImageFormats: 'Supports PDF, PNG, JPG formats',
      additionalNotes: 'Additional Notes',
      enterNotes: 'Enter additional notes (optional)',
      issueQuantity: 'Issue Quantity',
      autoListMarket: 'Auto-list to Market',
      issueToken: 'Issue Token',
      batchIssue: 'Batch Issue',
      inventoryNumber: 'Inventory Number',
      inventoryType: 'Inventory Type',
      selectInventoryType: 'Please select inventory type',
      rawMaterial: 'Raw Material',
      workInProgress: 'Work in Progress',
      finishedProduct: 'Finished Product',
      itemDescription: 'Item Description',
      enterItemDescription: 'Enter item description',
      valuationAmount: 'Valuation Amount',
      enterValuation: 'Enter valuation amount',
      warehouseLocation: 'Warehouse/Location',
      enterWarehouse: 'Enter warehouse name or location',
      photoQualityReport: 'Photo/Quality Report',
      clickToUploadImage: 'Click to upload or drag image here',
      dragImageHere: 'Click to upload or drag image here',
      imageFormats: 'Supports PNG, JPG, JPEG formats',
      recentIssuances: 'Recent Issuances',
      noIssuanceRecords: 'No issuance records',
      issuanceWillShowHere: 'Issuances will appear here after token issuance',
      issued: 'Issued',
      listed: 'Listed',
      copyHash: 'Copy Hash',
      viewTransaction: 'View Transaction',
      issuanceSuccess: 'Issuance Successful!',
      tokenIssuedSuccessfully: 'Token has been successfully issued to blockchain',
      tokenId: 'Token ID',
      transactionHash: 'Transaction Hash',
      nextSteps: 'Next Steps:',
      tokenRecordedOnBlockchain: 'Token has been recorded on blockchain',
      canViewInMarketTrading: 'Can be viewed in "Market Trading"',
      hashCanQueryDetails: 'Transaction hash can be used to query transaction details',
      confirm: 'Confirm',
      errors: {
        selectOrEnterDebtor: 'Please select or enter debtor name',
        enterReceivableAmount: 'Please enter accounts receivable amount',
        enterValidAmount: 'Please enter a valid amount (greater than 0)',
        selectDueDate: 'Please select due date',
        uploadContractInvoice: 'Please upload contract or invoice file',
        enterIssueQuantity: 'Please enter issue quantity',
        quantityMustBeAtLeastOne: 'Issue quantity must be at least 1',
        onlyPdfOrImage: 'Only PDF or image files are supported',
        selectInventoryType: 'Please select inventory type',
        enterItemDescription: 'Please enter item description',
        enterValuationAmount: 'Please enter valuation amount',
        enterValidValuation: 'Please enter a valid amount (greater than 0)',
        enterWarehouseLocation: 'Please enter warehouse/location',
        uploadPhotoOrReport: 'Please upload photo or quality report',
        onlyImageFiles: 'Only image files are supported',
      },
    },
    absPackaging: {
      title: 'ABS Packaging Platform',
      bankOnly: 'Bank Only',
      nbfiPurchase: 'NBFI Purchase',
      bankDescription: 'Package accounts receivable and inventory tokens into ABS tokens of different risk levels',
      nbfiDescription: 'Browse and purchase ABS token products issued by banks',
    },
    bridge: {
      title: 'Cross-Chain Bridge Management',
      bankDescription: 'Bridge your packaged ABS tokens',
      nbfiDescription: 'Bridge your purchased ABS tokens',
      bridgeTotal: 'Total Bridged',
      bridgeFee: 'Bridge Fee',
      bridgeableAssets: 'Bridgeable Assets',
      bridgeConfig: 'Bridge Configuration',
      bridgeHistory: 'Bridge History',
      selectedAssets: 'Selected Assets',
      selectedValue: 'Selected Total Value',
      estimatedReceived: 'Estimated Received',
      estimatedTime: 'Estimated Time',
      targetChain: 'Target Blockchain',
      recipientAddress: 'Recipient Address',
      addressValid: 'Valid Address',
      addressInvalid: 'Please enter a valid Ethereum address',
      previewBridge: 'Preview Bridge',
      confirmBridge: 'Confirm Bridge',
      inProgress: 'In Progress',
      completed: 'Completed',
      failed: 'Failed',
      viewDetail: 'View Details',
      bridgeId: 'Bridge ID',
      bridgeQuantity: 'Bridge Quantity',
      totalValue: 'Total Value',
      txHash: 'Transaction Hash',
      viewTransaction: 'View Transaction',
      filterByType: 'Filter by Type',
      filterByTranche: 'Filter by Tranche',
      allTypes: 'All',
      receivableABS: 'Receivable ABS',
      inventoryABS: 'Inventory ABS',
      allTranches: 'All',
      senior: 'Senior',
      mezzanine: 'Mezzanine',
      junior: 'Junior',
      holdingQuantity: 'Holding Quantity',
      tokenValue: 'Token Value',
      bridgeQuantityLabel: 'Bridge Quantity',
      sourceChain: 'Source Chain',
      bridgeSummary: 'Bridge Summary',
      bridgeAssets: 'Bridge Assets',
      feeDetails: 'Fee Details',
      assetValue: 'Asset Value',
      estimatedArrival: 'Estimated Arrival',
      status: 'Status',
      timestamp: 'Timestamp',
      progress: 'Bridge Progress',
      chainConfirm: 'Consortium Chain Confirmation',
      crossChaining: 'Cross-Chaining',
      targetConfirm: 'Target Chain Confirmation',
      finish: 'Finish',
      bridgePreview: 'Bridge Preview',
      estimatedTimeValue: 'Approximately 15 minutes',
      basicInfo: 'Basic Information',
      bridgeDetails: 'Bridge Details',
      transactionInfo: 'Transaction Information',
      transactionHash: 'Transaction Hash',
      copyHash: 'Copy Hash',
      viewOnExplorer: 'View on Explorer',
      reBridge: 'Re-bridge',
      initiateBridgeRequest: 'Initiate Bridge Request',
      allianceChainConfirmation: 'Alliance Chain Confirmation',
    },
    fundRecovery: {
      title: 'Fund Recovery & Forex Exchange Platform',
      description: 'Process USDC repatriation and conversion from external public chains',
      usdcBalanceOverview: 'USDC Balance Overview',
      currentBalance: 'Current Balance',
      todayConvertibleQuota: 'Today\'s Convertible Quota',
      unlimited: 'Unlimited',
      currentExchangeRate: 'Current Exchange Rate',
      conversionForm: 'Conversion Form',
      bankDirectConversion: 'Bank Direct Conversion (Circle)',
      nbfiForexPoolConversion: 'NBFI Forex Pool Conversion',
      conversionAmount: 'Conversion Amount (USDC)',
      circleAccountAddress: 'Circle Account Address',
      estimatedHandlingFee: 'Estimated Handling Fee',
      feeRate: 'Fee Rate:',
      feeAmount: 'Fee Amount:',
      forexPoolSelection: 'Forex Pool Selection',
      currentPoolDepth: 'Current Pool Depth:',
      exchangeRate: 'Exchange Rate:',
      autoMatchOptimalPool: 'Auto-matched Optimal Pool',
      estimatedReceiveEHKD: 'Estimated Receive eHKD',
      afterDeduction: 'After Fee Deduction',
      noHandlingFee: 'No Handling Fee (Bank Privilege)',
      handlingFeeNote: 'Handling Fee 1.2%, Estimated Arrival: 2-5 minutes',
      previewConversion: 'Preview Conversion',
      confirmConversion: 'Confirm Conversion',
      convertNow: 'Convert Now',
      conversionSuccess: 'Conversion Successful!',
      eHKDReceived: 'eHKD Successfully Received',
      conversionPath: 'Conversion Path',
      amountDetails: 'Amount Details',
      estimatedArrivalTime: 'Estimated Arrival Time',
      instantArrival: 'Instant Arrival (Circle Direct)',
      forexPoolProcessing: '2-5 minutes (Forex Pool Processing)',
      processing: 'Processing...',
      enterValidAmount: 'Please enter a valid conversion amount',
      exceedDailyLimit: 'Exceeds Daily Limit',
      recoveryHistory: 'Recovery History',
      timeline: 'Timeline',
      table: 'Table',
      type: 'Type',
      amount: 'Amount',
      transactionHash: 'Transaction Hash',
      copyHash: 'Copy Hash',
      usdcDeposit: 'USDC Deposit',
      forexExchange: 'Forex Exchange',
      completed: 'Completed',
      inProgress: 'In Progress',
      failed: 'Failed',
      forexPoolStatus: 'Forex Pool Status',
      totalLiquidity: 'Total Liquidity',
      dailyTradingVolume: '24h Trading Volume',
      dailyRateFluctuation: '24h Rate Fluctuation',
      myLiquidity: 'My Liquidity',
      myLiquidityContribution: 'My Liquidity Contribution',
      todayFeeRevenue: 'Today\'s Fee Revenue',
      annualizedYield: 'Annualized Yield',
      addRemoveLiquidity: 'Add/Remove Liquidity',
      poolDepthChart: 'Pool Depth Chart',
      realTimeConversionActivity: 'Real-time Conversion Activity',
      liquidityManagement: 'Liquidity Management',
      operationType: 'Operation Type',
      addLiquidity: 'Add Liquidity',
      removeLiquidity: 'Remove Liquidity',
      liquidityAmount: 'Amount (eHKD)',
      enterLiquidityAmount: 'Enter amount',
      addLiquidityNote: 'Adding liquidity earns fee revenue',
      annualizedYieldNote: 'Annualized yield ~3.7%',
      canRemoveAnytime: 'Can remove liquidity anytime',
      removeLiquidityNote: 'Removing liquidity stops fee revenue',
      fundsReturned: 'Funds will be returned immediately',
      minutesAgo: 'minutes ago',
      success: 'Success',
      fullAccess: 'Full Access',
      adminDescription: 'Administrator can use all conversion methods',
    },
    lending: {
      title: 'Lending Management',
      myCollateralizedLoans: 'My Collateralized Loans',
      applyForNewLoan: 'Apply for New Loan',
      loanMarket: 'Loan Market',
      myLoanManagement: 'My Loan Management',
      loanId: 'Loan ID',
      collateralToken: 'Collateral Token',
      loanAmount: 'Loan Amount',
      interestRate: 'Interest Rate',
      loanTerm: 'Loan Term',
      status: 'Status',
      operations: 'Operations',
      inReview: 'In Review',
      loanGranted: 'Loan Granted',
      repaying: 'Repaying',
      overdue: 'Overdue',
      earlyRepayment: 'Early Repayment',
      selectCollateralToken: 'Select Collateral Token',
      totalCollateralValue: 'Total Collateral Value',
      maxBorrowableAmount: 'Max Borrowable Amount',
      estimatedInterest: 'Estimated Interest',
      submitApplication: 'Submit Application',
      bid: 'Bid',
      borrower: 'Borrower',
      riskScore: 'Risk Score',
      currentLowestRate: 'Current Lowest Rate',
      bidRate: 'Bid Rate',
      bidAmount: 'Bid Amount',
      confirmBid: 'Confirm Bid',
      loanDetails: 'Loan Details',
      basicInfo: 'Basic Information',
      collateralInfo: 'Collateral Information',
      repaymentPlan: 'Repayment Plan',
      transactionRecords: 'Transaction Records',
      nbfiDescription: 'Manage your collateralized loans and apply for new loans',
      bankDescription: 'Manage your lending business and bid on new loan applications',
      lender: 'Lender',
      switchRoleHint: 'Please switch user role to "NBFI" or "Bank" in the top navigation bar',
      adminDescription: 'Administrator can view all lending management functions',
      fullAccess: 'Full Access',
      nbfiView: 'NBFI View (Borrower)',
      bankView: 'Bank View (Lender)',
      pendingBid: 'Pending Bid',
      bidding: 'Bidding',
      matched: 'Matched',
      normal: 'Normal',
      warning: 'Warning',
      viewDetail: 'View Detail',
      collection: 'Collection',
      totalLentAmount: 'Total Lent Amount',
      totalInterest: 'Total Interest',
      badDebtRate: 'Bad Debt Rate',
      loanStatistics: 'Loan Statistics',
      loanDistribution: 'Loan Distribution',
      noData: 'No Data',
      noLoanRecords: 'No Loan Records',
      noPendingApplications: 'No Pending Loan Applications',
      bidableApplications: 'Bidable Loan Applications',
      collateralTokens: 'Collateral Tokens',
      totalCollateralValueLabel: 'Total Collateral Value:',
      loanTermDays: 'Loan Term:',
      loanTermDaysUnit: 'days',
      borrowerLabel: 'Borrower:',
      riskScoreLabel: 'Risk Score:',
      currentLowestRateLabel: 'Current Lowest Rate:',
      lowRisk: 'Low Risk',
      mediumRisk: 'Medium Risk',
      highRisk: 'High Risk',
      annualized: 'Annualized',
      issueDate: 'Issue Date',
      dueDate: 'Due Date',
      bidTitle: 'Bid',
      applicationInfo: 'Loan Application Information',
      applicationId: 'Application ID:',
      loanAmountLabel: 'Loan Amount:',
      loanTermLabel: 'Loan Term:',
      currentLowestRateLabel2: 'Current Lowest Rate:',
      bidRateLabel: 'Bid Rate',
      required: '*',
      enterRate: 'Enter Rate',
      annualizedUnit: '% Annualized',
      rateTooHigh: 'Your rate is higher than the current lowest rate, may not win the bid',
      bidAmountLabel: 'Bid Amount',
      partialBid: 'Partial Bid',
      enterBidAmount: 'Enter Bid Amount',
      maxBidable: 'Max Bidable:',
      bidAmountExceeded: 'Bid amount cannot exceed loan amount',
      estimatedInterestIncome: 'Estimated Interest Income:',
      estimatedTotalRecovery: 'Estimated Total Recovery:',
      submitBid: 'Submit Bid',
      rateRangeError: 'Rate must be between 0-20%',
      amountRangeError: 'Bid amount must be between 0-{amount} eHKD',
      rateTooHighConfirm: 'Your rate {rate}% is higher than the current lowest rate {lowestRate}%, may not win the bid. Continue?',
      loanDetailTitle: 'Loan Details',
      loanIdLabel: 'Loan ID:',
      borrowerLabel2: 'Borrower:',
      loanAmountLabel2: 'Loan Amount:',
      interestRateLabel: 'Interest Rate:',
      annualizedUnit2: 'Annualized',
      collateralValue: 'Collateral Value:',
      loanTermLabel2: 'Loan Term:',
      daysUnit: 'days',
      issueDateLabel: 'Issue Date:',
      dueDateLabel: 'Due Date:',
      applicationDate: 'Application Date:',
      statusLabel: 'Status:',
      tokenId: 'Token ID',
      type: 'Type',
      value: 'Value',
      realTimeValue: 'Real-time Value',
      principal: 'Principal:',
      interestEstimated: 'Interest (Estimated):',
      total: 'Total:',
      applicationSubmitted: 'Application Submitted',
      loanGranted2: 'Loan Granted',
      fundsReceived: 'Funds Received',
      initiateLiquidation: 'Initiate Collateral Liquidation',
      close: 'Close',
      collateralValueLabel: 'Collateral Value',
      term: 'Term',
      noLoanRecords2: 'No Loan Records',
      currentValue: 'Current Value:',
      selectAtLeastOneToken: 'Please select at least one collateral token',
      loanAmountExceeded: 'Loan amount cannot exceed max borrowable amount {amount} eHKD',
      enterLoanAmount: 'Enter Loan Amount',
      loanTermLabel3: 'Loan Term',
      days7: '7 days',
      days30: '30 days',
      days90: '90 days',
      days180: '180 days',
      estimatedInterestLabel: 'Estimated Interest:',
      basedOnMarketRate: 'Based on current market rate {rate}%',
      loanStatistics2: 'Loan Statistics',
      myTotalLoanAmount: 'My Total Loan Amount',
      availableCollateral: 'Available Collateral',
      currentAverageRate: 'Current Average Rate',
      repaymentCalendar: 'Repayment Calendar',
      noUpcomingLoans: 'No Upcoming Loans',
      repaymentRequired: 'Repayment Required:',
      receivable: 'Accounts Receivable',
      inventory: 'Inventory',
    },
    marketTrading: {
      title: 'Market Trading',
      marketOverview: 'Market Overview',
      tokenFilters: 'Token Filters',
      watchlist: 'Watchlist',
      recentTrades: 'Recent Trades',
      filterByType: 'Filter by Type',
      filterByStatus: 'Filter by Status',
      allTypes: 'All',
      receivable: 'Receivable',
      inventory: 'Inventory',
      allStatus: 'All',
      onSale: 'On Sale',
      soldOut: 'Sold Out',
      searchPlaceholder: 'Search tokens...',
      purchase: 'Purchase',
      price: 'Price',
      quantity: 'Quantity',
      issuer: 'Issuer',
      purchaseModal: {
        title: 'Purchase Token',
        tokenInfo: 'Token Information',
        purchaseQuantity: 'Purchase Quantity',
        totalAmount: 'Total Amount',
        confirmPurchase: 'Confirm Purchase',
        purchaseSuccess: 'Purchase Successful!',
        transactionSuccess: 'Transaction Successful!',
        tokenPurchaseCompleted: 'Token purchase completed',
        transactionHash: 'Transaction Hash',
        copyHash: 'Copy Hash',
        confirmPurchaseTitle: 'Confirm Purchase',
        unitPrice: 'Unit Price:',
        quantity: 'Quantity:',
        subtotal: 'Subtotal:',
        platformFee: 'Platform Fee (1%):',
        total: 'Total:',
        processing: 'Processing...',
        cancel: 'Cancel',
      },
      description: 'Browse and trade accounts receivable tokens and inventory tokens',
      tradableTokens: 'Tradable Tokens',
      batchPurchase: 'Batch Purchase',
      debtor: 'Debtor',
      faceValue: 'Face Value',
      dueDate: 'Due Date',
      remaining: 'Remaining',
      days: 'days',
      annualYield: 'Annual Yield',
      riskRating: 'Risk Rating',
      inventoryType: 'Inventory Type',
      item: 'Item',
      valuation: 'Valuation',
      storageLocation: 'Storage Location',
      qualityStatus: 'Quality Status',
      addToWatchlist: 'Add to Watchlist',
      removeFromWatchlist: 'Remove from Watchlist',
      marketTotalVolume: 'Market Total Volume',
      activeTokenCount: 'Active Token Count',
      tokens: 'tokens',
      todayTransactionCount: 'Today\'s Transaction Count',
      transactions: 'transactions',
      platformTotalCommission: 'Platform Total Commission',
      today: '(Today)',
      marketChange24h: '24h Market Change',
      comparedToYesterday: 'Compared to Yesterday',
      filterConditions: 'Filter Conditions',
      reset: 'Reset',
      tokenType: 'Token Type',
      riskLevel: 'Risk Level',
      all: 'All',
      lowRisk: 'Low Risk',
      mediumRisk: 'Medium Risk',
      highRisk: 'High Risk',
      issuer: 'Issuer',
      priceRange: 'Price Range',
      dueTime: 'Due Time',
      withinDays: 'days',
      myWatchlist: 'My Watchlist',
      noWatchedTokens: 'No watched tokens',
      clickStarToAdd: 'Click the star on token card to add',
      remove: 'Remove',
      recentTransactions: 'Recent Transactions',
      noTransactionRecords: 'No transaction records',
      marketTrend: 'Market Trend (7 days)',
      price: 'Price',
      monday: 'Mon',
      tuesday: 'Tue',
      wednesday: 'Wed',
      thursday: 'Thu',
      friday: 'Fri',
      saturday: 'Sat',
      sunday: 'Sun',
      buyNow: 'Buy Now',
      setPriceAlert: 'Set Price Alert',
      certified: 'Certified',
      pendingCertification: 'Pending Certification',
      currentPrice: 'Current Price',
      discount: 'Discount',
      receivable: 'Accounts Receivable',
      inventory: 'Inventory',
      sampleDebtors: {
        abcTech: 'ABC Technology Co., Ltd.',
        xyzEngineering: 'XYZ Engineering Group',
        defConstruction: 'DEF Construction Co., Ltd.',
      },
      sampleIssuers: {
        coreEnterpriseA: 'Core Enterprise A',
        coreEnterpriseB: 'Core Enterprise B',
        coreEnterpriseC: 'Core Enterprise C',
        constructionCompanyX: 'Construction Company X',
        constructionCompanyY: 'Construction Company Y',
        constructionCompanyZ: 'Construction Company Z',
      },
      inventoryTypes: {
        finishedProduct: 'Finished Product',
        rawMaterial: 'Raw Material',
        workInProgress: 'Work in Progress',
      },
      inventoryItems: {
        constructionSteel: 'Construction Steel',
        cement: 'Cement',
        precastComponents: 'Precast Components',
      },
      storageLocations: {
        shenzhenWarehouseA: 'Shenzhen Warehouse A',
        guangzhouWarehouseB: 'Guangzhou Warehouse B',
        dongguanFactoryC: 'Dongguan Factory C',
      },
      qualityStatuses: {
        certified: 'Certified',
        pendingCertification: 'Pending Certification',
      },
    },
    absPackaging: {
      title: 'ABS Packaging Platform',
      description: 'Package accounts receivable and inventory tokens into ABS tokens of different risk levels',
      bankOnly: 'Bank Only',
      nbfiPurchase: 'NBFI Purchase',
      bankDescription: 'Package accounts receivable and inventory tokens into ABS tokens of different risk levels',
      nbfiDescription: 'Browse and purchase ABS token products issued by banks',
      assetPool: 'Available Asset Pool',
      absBuilder: 'ABS Builder',
      packagedABSList: 'Packaged ABS List',
      selectedAssets: 'Selected Assets',
      totalValue: 'Total Value',
      averageRiskRating: 'Average Risk Rating',
      absName: 'ABS Name',
      packagingScale: 'Packaging Scale',
      riskLayering: 'Risk Layering Configuration',
      seniorTranche: 'Senior Tranche',
      mezzanineTranche: 'Mezzanine Tranche',
      juniorTranche: 'Junior Tranche',
      interestRate: 'Interest Rate',
      previewABS: 'Preview ABS',
      confirmPackaging: 'Confirm Packaging',
      packagingSuccess: 'Packaging Successful!',
      issuanceTime: 'Issuance Time',
      totalScale: 'Total Scale',
      layerStatus: 'Layer Status',
      soldOut: 'Sold Out',
      inSale: 'In Sale',
      notStarted: 'Not Started',
      receivableTab: 'Accounts Receivable',
      inventoryTab: 'Inventory',
      searchTokenId: 'Search Token ID...',
      riskLevel: 'Risk Level',
      all: 'All',
      lowRisk: 'Low Risk (Grade A)',
      mediumRisk: 'Medium Risk (Grade B)',
      highRisk: 'High Risk (Grade C)',
      amountRange: 'Amount Range',
      issuer: 'Issuer',
      selectedTotalValue: 'Selected Total Value:',
      selectedCount: 'Selected:',
      packagingConfig: 'Packaging Configuration',
      absNameLabel: 'ABS Name',
      absNamePlaceholder: 'e.g., Receivable ABS-2025-001',
      assetType: 'Asset Type',
      autoDetermined: '(Auto-determined based on selected assets)',
      basedOnSelectedAssets: 'Auto-calculated based on total value of selected assets',
      expectedYield: 'Expected Yield',
      aaaRating: 'AAA',
      bbbRating: 'BBB',
      bbRating: 'BB',
      fixedPercentage: 'Fixed percentage (remaining part), auto-calculated',
      remainingPart: 'Remaining Part',
      autoCalculated: 'Auto-calculated',
      tranchePreview: 'Tranche Preview',
      amount: 'Amount:',
      percentage: 'Percentage:',
      issuanceSettings: 'Issuance Settings',
      allowNBFIPurchase: 'Allow NBFI Purchase',
      allowNBFIPurchaseDesc: 'Allow non-bank financial institutions to purchase this ABS',
      autoListMarket: 'Auto-list on Market',
      autoListMarketDesc: 'Automatically list on trading market after packaging',
      notes: 'Notes',
      notesPlaceholder: 'Enter notes (optional)',
      reset: 'Reset',
      requirements: 'Please complete the following requirements:',
      atLeastTwoAssets: 'Select at least 2 assets',
      atLeastTwoIssuers: 'Select at least 2 assets from different issuers to diversify risk',
      enterAbsName: 'Enter ABS name',
      myAbsProducts: 'My ABS Products',
      noAbsProducts: 'No ABS Products',
      willShowAfterPackaging: 'Will show here after packaging',
      type: 'Type:',
      viewDetail: 'View Detail',
      report: 'Report',
      purchasableAbsProducts: 'Purchasable ABS Products',
      browseAbsProducts: 'Browse ABS token products issued by banks, select suitable investment targets',
      basicInfo: 'Basic Information',
      packagingScaleLabel: 'Packaging Scale:',
      assetCount: 'Asset Count:',
      selectedAssetList: 'Selected Assets',
      tokenId: 'Token ID',
      typeLabel: 'Type',
      faceValue: 'Face Value',
      riskRating: 'Risk Rating',
      trancheConfig: 'Risk Layering Configuration',
      allowNBFI: 'Allow NBFI Purchase:',
      autoList: 'Auto-list Market:',
      transactionHash: 'Transaction Hash',
      copyHash: 'Copy Hash',
      nextSteps: 'Next Steps:',
      absRecordedOnBlockchain: 'ABS tokens have been recorded on blockchain',
      canViewInList: 'Can view details in "Packaged ABS List"',
      hashCanQueryDetails: 'Transaction hash can be used to query transaction details',
      confirm: 'Confirm',
      cancel: 'Cancel',
      packaging: 'Confirm Packaging',
      processing: 'Packaging...',
      receivableABS: 'Receivable ABS',
      inventoryABS: 'Inventory ABS',
      mixedABS: 'Mixed ABS',
      senior: 'Senior',
      mezzanine: 'Mezzanine',
      junior: 'Junior',
      seniorTrancheLabel: 'Senior Tranche',
      mezzanineTrancheLabel: 'Mezzanine Tranche',
      juniorTrancheLabel: 'Junior Tranche',
      daysRemaining: 'days remaining',
      status: 'Status:',
    },
    pages: {
      marketTrading: 'Market Trading',
      lending: 'Lending',
      fundRecovery: 'Fund Recovery',
    },
    roleSelection: {
      title: 'Blockchain Asset Tokenization Platform',
      subtitle: 'v1.0 · Five-Role Collaborative Demo System',
      description: 'Click on the role cards below to experience different participant perspectives',
      responsibilities: 'Core Responsibilities',
      permissions: 'Permission Features',
      enterButton: 'Enter',
      demoMode: 'Demo Mode',
      fullDemo: 'Full Process Demo',
      quickDemo: 'Quick Feature Demo',
      freeExplore: 'Free Exploration Mode',
      platformStats: 'Platform Statistics',
      totalAssets: 'Total Platform Assets',
      dailyVolume: 'Daily Trading Volume',
      activeUsers: 'Active Users',
      bridgeVolume: 'Total Bridge Volume',
      resetData: 'Reset All Demo Data',
      exportRecord: 'Export Demo Record',
      switchTheme: 'Switch to',
      businessFlow: 'Platform Core Business Flow',
      assetIssuance: 'Asset Issuance',
      marketTrading: 'Market Trading',
      absPackaging: 'ABS Packaging',
      lending: 'Lending',
      bridge: 'Cross-Chain Bridge',
      fundRecovery: 'Fund Recovery',
      confirmReset: 'Are you sure you want to reset all demo data?',
      fullDemoDesc: '30 minutes, following business process',
      quickDemoDesc: '10 minutes, key features',
      freeExploreDesc: 'No time limit',
      darkTheme: 'Dark Theme',
      lightTheme: 'Light Theme',
    },
    common: {
      minutes: 'minutes',
      normal: 'Normal',
      addressBook: 'Address Book',
      advancedOptions: 'Advanced Options',
      slippageProtection: 'Slippage Protection',
      default: 'Default',
      gasStrategy: 'Gas Strategy',
      standard: 'Standard',
      fast: 'Fast',
      custom: 'Custom',
      items: 'items',
      history: 'History',
      targetChain: 'Target Chain',
      quantity: 'Quantity',
      value: 'Value',
      chainConfirming: 'Chain Confirming',
      blocks: 'blocks',
    },
  },
}

export function getTranslation(lang: Language): Translations {
  return translations[lang] || translations.zh
}

export function t(lang: Language, key: string): string {
  const keys = key.split('.')
  let value: any = translations[lang]
  
  for (const k of keys) {
    value = value?.[k]
    if (value === undefined) {
      // 如果找不到，尝试使用中文版本
      value = translations.zh
      for (const k2 of keys) {
        value = value?.[k2]
      }
      break
    }
  }
  
  return typeof value === 'string' ? value : key
}
